### ISSUE TITLE
Tambah volte

### ISSUE THREAD

**Issue by exodius48** [mfaishalakbar/MIUI8-LTE-Enabler#1]
Tambah volte bro biar makin tamvan. :v

**Comment by mfaishalakbar** [comment]
I thought VoLTE Button feature fix was added since version v1.0 . Please recheck again :D

Kayaknya dah dari awal release dah ada deh. 

https://puu.sh/siDGs/1b7d36753b.png

**Comment by exodius48** [comment]
ane kan blm nyoba, kali aja blm ada. btw gak usah pakek bhs inggris. :v
